geometry: set offsetUnit
Fixes:
lsst.pex.exceptions.exceptionsLib.LsstCppException: Validation error (1 error):
 * Ccd.offsetUnit: no value available for required parameter